//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace practice
{
    using System;
    using System.Collections.Generic;
    
    public partial class furniture
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public furniture()
        {
            this.furnitureWarehouse = new HashSet<furnitureWarehouse>();
            this.productFurniture = new HashSet<productFurniture>();
        }
    
        public int idFurniture { get; set; }
        public string article { get; set; }
        public string nameFurniture { get; set; }
        public string typeFurniture { get; set; }
        public double width { get; set; }
        public Nullable<double> length { get; set; }
        public Nullable<double> weight { get; set; }
        public string image { get; set; }
        public decimal price { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<furnitureWarehouse> furnitureWarehouse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<productFurniture> productFurniture { get; set; }
    }
}
