//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace practice
{
    using System;
    using System.Collections.Generic;
    
    public partial class furnitureWarehouse
    {
        public int idParty { get; set; }
        public int idFurniture { get; set; }
        public int QTY { get; set; }
    
        public virtual furniture furniture { get; set; }
    }
}
