//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace practice
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public int numberOrder { get; set; }
        public System.DateTime date { get; set; }
        public string executionStage { get; set; }
        public string customer { get; set; }
        public string manager { get; set; }
        public Nullable<decimal> price { get; set; }
    
        public virtual customProducts customProducts { get; set; }
        public virtual user user { get; set; }
    }
}
